# Generated by Django 4.2.5 on 2023-11-09 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='static/img/Papahe/productos_gastronomicos/')),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='static/img/Papahe/productos_medicinales/')),
                ('farmacia', models.CharField(max_length=30)),
                ('posologia', models.CharField(max_length=50)),
                ('presentacion', models.CharField(max_length=25)),
                ('ingredientes', models.CharField(max_length=256)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('userType', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogoType', models.BooleanField(default=False)),
                ('productGas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papahe_app.productgas')),
                ('productMed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papahe_app.productmed')),
            ],
        ),
    ]
