# Generated by Django 4.2.5 on 2023-11-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papahe_app', '0002_delete_user_alter_productgas_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmed',
            name='categoria',
            field=models.CharField(choices=[('BAJAR DE PESO', 'Bajar de Peso'), ('RESFRIADO', 'Resfriado'), ('INFECCION URINARIA', 'Infección Urinaria'), ('MULTIVITAMÍNICO', 'Multivitamínico'), ('ENERGIZANTES', 'Energizantes'), ('COLON', 'Colon'), ('GÁSTRICOS', 'Gástricos'), ('ESTREÑIMIENTO', 'Estreñimiento'), ('TRANQUILIZANTES', 'Tranquilizantes'), ('INSOMNIO', 'Insomnio'), ('REUMÁTICOS', 'Reumáticos'), ('ÓSEOS', 'Óseos'), ('REGENERADORES', 'Regeneradores'), ('LIMPIADORES ORGÁNICOS', 'Limpiadores Orgánicos'), ('RENAL', 'Renal'), ('HEPATOPROTECTORES', 'Hepatoprotectores'), ('CORESTEROL Y TRIGLICÉRIDOS', 'Colesterol y Triglicéridos'), ('CONCENTRACIÓN', 'Concentración'), ('MEJORADORES DE LA CIRCULACIÓN', 'Mejoradores de la Circulación'), ('HIPERTENSIÓN', 'Hipertensión'), ('DIABETES', 'Diabetes'), ('SALUD FEMENINA', 'Salud Femenina'), ('SALUD MASCULINA', 'Salud Masculina'), ('PRODUCTOS NATURALES', 'Productos Naturales'), ('SHAMPOO Y ACONDICIONADORES', 'Shampoo y Acondicionadores'), ('LOCIONES', 'Lociones'), ('', 'Sin Categoría')], default='', max_length=50),
        ),
    ]
