# Generated by Django 4.2.5 on 2023-11-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papahe_app', '0004_alter_productmed_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmed',
            options={'ordering': ['categoria', 'nombre']},
        ),
    ]
