# Generated by Django 4.2.7 on 2023-11-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papahe_app', '0008_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmed',
            name='posologia',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='productmed',
            name='presentacion',
            field=models.CharField(max_length=50),
        ),
    ]
